### PR TITLE
Remove \n from certs, signature addition without ds NS

### PR DESCRIPTION
**Pull request by stephenbradshaw**
Fixes for a few issues found when using this library to attempt some SAML attacks against a Microsoft (login.microsoft.com - Azure Active Directory) delivered SAML Response during a security assessment of a third party product consuming AAD authentication.

The Microsoft generated SAML did not use a ds namespace in the SAML request, which caused some problems when trying to re-sign messages using the same XML template. Made some changes in the code that queries the xml template to find the placeholder node to work more independently of namespaces.

Also, added code to also strip newline characters from PEM certificates.

### CODE REVIEW

**Comment by stephenbradshaw** [comment]
Also added an optional parameter to modify the namespace dictionary on XmlSigner

**Comment by kislyuk** [comment]
Thanks for your contribution. Can you please add a test case or at least give me a signed document that can be used to regression test this?

**Comment by stephenbradshaw** [comment]
See attached xml file. This is in the form of a SAML response provided by the Microsoft online service, however with sanitised details and signed using my own generated key, using the signxml modified code in the PR. The signature should be verifiable using the embedded cert.
[signed.txt](https://github.com/XML-Security/signxml/files/4750727/signed.txt)

`XMLSigner(method=signxml.methods.enveloped, c14n_algorithm='http://www.w3.org/2001/10/xml-exc-c14n#', namespaces={None:'http://www.w3.org/2000/09/xmldsig#'}).sign(xml_root, key=key, cert=cert, reference_uri=reference)`

**Comment by keke8273** [comment]
This is exactly what i am looking for. Any idea when to merge and release this PR?

**Comment by kislyuk** [comment]
This PR contains a hodgepodge of changes that I am not comfortable merging together. Each change will have to be merged separately with a test case. I maintain this library for free in my spare time and I do not have the bandwidth to develop test cases for these changes; if faster turnaround on these changes is needed, complete single-feature review-friendly PRs are always welcome, and if my work is needed, the sponsor button is at the top of the page.

Aside from splitting the PR into individual changes with test cases, there should be no mutable keyword arguments (use a `None` placeholder instead and set the default value in the body of the function/method).

**Comment by stephenbradshaw** [comment]
Fair enough. Will close this PR and resubmit once I have had a chance to redo.

**Comment by keke8273** [comment]
For those of you just wanna drop the `ds` namespace prefix. Create a signer object and change its `namespaces` property before sign the xml. 
`
xml_signer = XMLSigner()
xml_signer.namespaces = {None:'http://www.w3.org/2000/09/xmldsig#'}
`

**Pull request closed without merging**
