### PR TITLE
Allow multiple c14n algorithms

### PR DESCRIPTION
**Pull request by hathawsh**
I'm working with a service that transmits and receives signed XML with very specific requirements. One of the requirements is to use different canonicalization algorithms for the signed info and for the payload. With this patch, `signxml` can be configured to be compatible with the requirement.

### CODE REVIEW

**Comment by kislyuk** [comment]
Thanks for your contribution!

I understand your requirement and I would like to support it. we need to clarify the names of the resulting options. Also, this PR can't be merged without a test case.

I think it would be better to organize the options as follows:
```
class XMLSigner(...):
    def __init__(
        self,
        signature_c14n_algorithm=XMLSignatureProcessor.default_c14n_algorithm,
        payload_c14n_algorithm=XMLSignatureProcessor.default_c14n_algorithm
    ):
        self.signature_c14n_algorithm = "http://www.w3.org/2006/12/xml-c14n11"
        self.payload_c14n_algorithm = "http://www.w3.org/2006/12/xml-c14n11"
        ...
```

**Comment by hathawsh** [comment]
If we change the option name, the change will be backward incompatible, so the next version should be 3.x rather than 2.11 (assuming we're following semantic versioning principles).

I would prefer to add an option and leave the existing option name, making the new version compatible with existing code.

**Comment by kislyuk** [comment]
This PR will not be accepted per the feedback above, but the functionality will be supported in the v3.0.0 release

**Comment by kislyuk** [comment]
Tracking in #205

**Pull request closed without merging**
