### PR TITLE
WIP: xades (ETSI) implementation

### LINKED ISSUE #90: XAdES support
* https://www.w3.org/TR/XAdES/

* https://en.wikipedia.org/wiki/XAdES

### PR DESCRIPTION
**Pull request by blaggacao**
- [x] Schemata
- [x] References
- [ ] Sign - SignedProperties (XAdES Baseline)
- [ ] Sign - SignedDataObjectProperties (XAdES Baseline) *
- [ ] Sign - UnsignedProperties (XAdES Baseline) *
- [ ] Sign - UnsignedDataObjectProperties (XAdES Baseline) *
- [ ] Verify (XAdES Baseline) *
- [ ] Augment (XAdES Baseline) *
- [ ] Sign (XAdES Extended)
- [ ] Verify (XAdES Extended) *
- [ ] Augment (XAdES Extended) *
- [ ] Test Cases (XAdES Baseline) *
- [ ] Test Cases (XAdES Extended) *
- [ ] Documentation

_\* kindly require patreon / sponsorship_

Closes #90

### CODE REVIEW

**Comment by blaggacao** [comment]
@kislyuk Maybe you can quickly validate if this goes into the right direction (on a general understanding of the matter), having Schemata & References added.

**Comment by blaggacao** [comment]
I plan to use the `from lxml.builder import ElementMaker` any objections (I might have overseen)?

**Comment by mileo** [comment]
Nice, take a look at https://github.com/m32/endesive/tree/master/endesive/xades

**Comment by blaggacao** [comment]
@mileo nice, thanks. Why do you use `get_rdns_name` instead of the certificates built-in RFC method? I've seen it several times now, but no explanation to why, so I assume it's just path dependency. Do you have any I insight?

**Comment by mileo** [comment]
@blaggacao i'm not the author of endevise but you can ask it to @m32.

If he don't answer it, i can help you to check why.

Best regards

**Comment by ovnicraft** [comment]
@blaggacao nice work, so its possible add what type of XADES are implementing on this PR ? i am available to work together.

**Comment by blaggacao** [comment]
@mileo thanks, I understand. Don't mind, I'll have it on the radar anyhow. Once I know the answer, I'll post back.

@ovnicraft, I'm planning to implement all XAdES baseline signature levels. And provide some kind of extensibility to work with extended signatures (such as BES, EPES and others). Implementation of extended signatures often depend on the concrete policy adopted, so some kind of hook might be best.

**Comment by blaggacao** [comment]
I need the base64 encoded DER representation of ASN.1 IssuerSerial type as defined in https://www.ietf.org/rfc/rfc5035.txt

Can anyone help me out how to produce this struct and how to DER encode it afterwards?

I've seen OpenSSL 3.0, once released, will have support for this struct, but that's not yet available.

**Comment by ovnicraft** [comment]
Maybe links to help:
* https://cryptography.io/en/latest/hazmat/primitives/asymmetric/serialization/#der
* http://snmplabs.com/pyasn1/pyasn1/codec/der/contents.html?highlight=der#pyasn1.codec.der.encoder.encode

**Comment by kislyuk** [comment]
@blaggacao the code overall looks good and I would encourage you to finish the PR if you can.

The links from @ovnicraft seem sufficient to answer your most recent question.

Also, the dependency version ranges are set specifically to match versions of binary packagess available in Ubuntu 18.04, please don't change them unless you have a specific reason.

Thanks for your work on this.

**Comment by blaggacao** [comment]
@kislyuk Thanks for your feedback. We'll be pushing this until a basic implementation serves our underlying use case.

Once we are there, and after some polishing, I'd ping you again for some final code review. Somewhere early next year.

Sorry for the deps, that might have been github's dependabot. Should be easily revertable.

@Deiber for such and review reasons, please care ***not*** to force push, even if it's _your_ branch. We can squash later without problem into a clean git history. Our commit msg standards shall _not_ apply until that squash, no worries :wink:

**Comment by ovnicraft** [comment]
@blaggacao  i added a PR in to help https://github.com/xoe-labs/signxml/pull/1

BTW i consider implementation must consider different signature forms:
* XAdES-BES
* XAdES-EPES
* XAdES-T
* XAdES-C

AFAIK reading your code, we need split some code (everything is done :100: )

**Comment by ovnicraft** [comment]
I am reading this: https://www.etsi.org/deliver/etsi_ts/101900_101999/101903/01.04.02_60/ts_101903v010402p.pdf at 4.4.2 mention:

image

so a posible solution:
*  `XAdESSigner` renamed to `XAdESBESSigner` 
* new class `XAdESEPESSigner`, here add `SignaturePolicyIdentifier` element redefining `_generate_xades_ssp_elements()`

So can be hackable :-)

**Comment by blaggacao** [comment]
You are right, the EPES + BES must be very extendable, it seems almost impossible to implement a generic solution for them as it might largely depend on the specific policy (although in practice they might converge to some emerging pattern).

On the other hand, I was hoping to find a way to make it somewhat generic or pass some factory (so strictly speaking) one could do an implementation in-tree surrounding current code and business logic (and it would be a well-defined api). But sub-classing isn't bad, neither.

**Comment by blaggacao** [comment]
@Deiber please do NOT force push. ;-)

**Comment by ovnicraft** [comment]
@Deiber can you check this: https://github.com/xoe-labs/signxml/pull/1

**Comment by Deiber** [comment]
@ovnicraft  @blaggacao  Sorry for the lateness reply,  I was checking other local issues related to, I'm going to check it out next week, probably the Monday :wink:

**Comment by ovnicraft** [comment]
@Deiber any news about this ?

**Comment by ovnicraft** [comment]
@blaggacao what do you think about this ? could be continued on this state ?

**Comment by pokoli** [comment]
Hi,

Thanks all who put some efforts on this work. 
I will like to know which is the state of this PR and if anyone is working on it? 
We need xades signature for one of our projects, so if nobody is working on it we may take the current work and continue. 

We are at planning phase and explorint the alternatives. We need some software to sign xml documents using xades and we prefer to contribute it to a well maintaned librarly than developing a custom solution. 

Reggards

**Comment by blaggacao** [comment]
Hi @pokoli I'm completely disengaged with rhis PR and it's basicalky unmaintained. Hence, feel free to take and own it.

**Comment by ovnicraft** [comment]
@pokoli sound great, also I opened this https://github.com/xoe-labs/signxml/pull/1, adding some info needed.

**Comment by pokoli** [comment]
Hi, I just updated the current PR to current develop branch and make the test suite pass. 
I have the fear that I broke some of the exiting functionality so before going further I will like to have some test suite to ensure that what was already. 

I guess I will need to create a xades folder in the `tests/interop` folder and include an include all the required tests there. My plan is to create a simple test case and start adding more about them. Is there any guideliness for writing tests cases? 

I see there is no documentation about how to run the xades signing. I think it will be great to include any. Can someone that already worked on such PR provide some example so I can include it (without reverse enginering the code). 

Thanks in advance.

**Comment by pokoli** [comment]
BTW: I pushed my work to https://github.com/pokoli/signxml/tree/xades 

I prefered to not create a new one until not requested. Maybe someone can give me access to the exsiting branch so I can update it or maybe the maintainers should update the branch of the pull request. In any case, let me know if something from my side is missing.

**Comment by pokoli** [comment]
I pushed new work which contains some basic testing and adapted the PR to latest tip functionalities. 
I will try to work on a validator soon to ensure everything works well.

**Comment by ovnicraft** [comment]
@pokoli great so can you open a new PR and link this one for the record, we can continue review and tests on yours.

**Comment by ovnicraft** [comment]
@pokoli Also about your code an DER-instance for types you can check this code https://github.com/xoe-labs/signxml/pull/1/files and re used to complete the job :)

**Comment by pokoli** [comment]
I had some time to continue working on it.. I've tested on a Electronic document signed with Xades and XMLVerify is capable of verifing it. But I'm not able to verify my own document on the tests suite: 

If I sue the `x509_cert=cert` I get the following result: 

```signxml.exceptions.InvalidSignature: Signature verification failed: bad signature```

but if I remove such argument I get: 

```OpenSSL.crypto.X509StoreContextError: [20, 0, 'unable to get local issuer certificate']```

Is expected to use the x509_cert argument in tests? Or how should I validate the signed document?

**Comment by kislyuk** [comment]
Thanks everyone for your work on this PR. XAdES support was added in v3.0.0 using a different code structure. Please test v3.0.0 and let us know whether it suits your needs.

**Pull request closed without merging**
